name: Persist Exchange Rate

on:  
  push:
    branches:
      - main
  schedule:
    - cron: '10,20,30,40,50 2 * * *'
    - cron: '0,10,20,30,40,50 3-14 * * *'

jobs:
  exchange-rate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    env:
      KOREAEXIM_API_KEY: ${{ secrets.KOREAEXIM_API_KEY }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

    steps:
      - name: Check API endpoint with curl
        run: |
          curl -v --location "https://www.koreaexim.go.kr/site/program/financial/exchangeJSON?authkey=${{ secrets.KOREAEXIM_API_KEY }}&searchdate=20250321&data=AP01"
      
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10
          run_install: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run job
        run: |
          pnpm run:exchange